### ISSUE TITLE
Rogue Globals

### ISSUE THREAD

**Issue by tenplus1** [Neuromancer56/hardcore_farming#1]
In the init.lua you have set globals 'replace_rate', 'interval' and 'chance' which may interfere with variable names setup by other mods that this one relies on.  Would it be possible to create a single global table and insert these variables inside instead to keep things tidy e.g.
```
hardware_farming = {
   replace_rate = tonumber(minetest.settings:get("eat_crops_delay")) or 15,
   interval = tonumber(minetest.settings:get("spawn_pests_delay")) or 50,
   chance = tonumber(minetest.settings:get("spawn_pests_probability")) or 10,
}
```
... and from there you can easily use hardware_farming.replace_rate and the like inside other files.

**Comment by Neuromancer56** [comment]
Thanks.  This has been fixed.
